import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar principal (docs/)
  
  // Sidebar para Proyecto
  proyectoSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  // Sidebar para Escenario
  escenarioSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  // Sidebar para Implementación
  implementacionSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  // Sidebar para Nosotros
  nosotrosSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar para Ataque
  ataqueSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;